### ISSUE TITLE
request - tests

### ISSUE THREAD

**Issue by kyleect** [testingrequired/restfile#8]
HTTP response messages

```yaml
name: Get Posts
description: Get all posts from the blog
http: |
  GET /posts HTTP/1.1
  Host: {{$ baseUrl}}
  Accept: application/json
  user-agent: {{$ userAgent}}
tests:
  shouldReturnPost: |
    HTTP/1.1 200 OK
    Date: Mon, 27 Jul 2009 12:28:53 GMT
    Server: Apache/2.2.14 (Win32)
    Content-Type: application/json
    Connection: Closed

    [{"text":"Hello Word!"}]
```

## TODO

- [ ] Populate variables, secrets and prompts in to `request.test.http` so they can be referenced in comparison
- [ ] Support `request.test` shorthand if there is only one test on the request
- [ ] Support wildcard syntax in the test `{{*}}` or `{{_}}`
